#!/bin/bash

# Example: Custom Survival Column Names
# This shows how to specify exact column names for survival analysis

echo "================================================"
echo "Example: Specifying Custom Survival Columns"
echo "================================================"
echo ""
echo "Scenario: Your data has non-standard column names"
echo "  - Survival time column: 'OS_months'"
echo "  - Survival event column: 'death_event'"
echo ""
echo "Command:"
echo ""
echo "Rscript nmf_analysis_cli.R \\"
echo "  --dataset MyDataset \\"
echo "  --expr_file /path/to/expression.txt \\"
echo "  --samples_annot_file /path/to/annotations.txt \\"
echo "  --surv_time_col 'OS_months' \\"
echo "  --surv_event_col 'death_event'"
echo ""
echo "================================================"
echo ""
echo "Other common survival column name examples:"
echo ""
echo "For overall survival:"
echo "  --surv_time_col 'OS_months' --surv_event_col 'OS_event'"
echo "  --surv_time_col 'overall_survival_days' --surv_event_col 'vital_status'"
echo ""
echo "For disease-free survival:"
echo "  --surv_time_col 'DFS_months' --surv_event_col 'recurrence'"
echo "  --surv_time_col 'disease_free_days' --surv_event_col 'relapse'"
echo ""
echo "For progression-free survival:"
echo "  --surv_time_col 'PFS_months' --surv_event_col 'progression'"
echo ""
echo "================================================"
echo ""
echo "Note: If you don't specify these parameters, the script"
echo "will try to auto-detect columns with common names like:"
echo "  - Time: DFS.m, survival, time, months"
echo "  - Event: recur, death, status, event"
echo "================================================"
