// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/whoami.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
var whoami_default = defineTool({
  name: "whoami",
  title: "Who am I",
  description: "Return the signed-in user's id and email.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const userId = ctx.getUserId();
    const email = ctx.getUserEmail();
    return {
      content: [{ type: "text", text: JSON.stringify({ userId, email }) }],
      structuredContent: { userId, email }
    };
  }
});

// src/lib/mcp/tools/list-analyses.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/_supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.90.1";
function supabaseForUser(ctx) {
  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
  return createClient(url, key, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function requireAuth(ctx) {
  if (!ctx.isAuthenticated()) {
    return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
  }
  return null;
}

// src/lib/mcp/tools/list-analyses.ts
var list_analyses_default = defineTool2({
  name: "list_analyses",
  title: "List NMF analyses",
  description: "List the signed-in user's saved NMF analyses (id, name, creation date, and summary size).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    const err = requireAuth(ctx);
    if (err) return err;
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("analyses").select("id, name, created_at, summary, survival_pvalue").order("created_at", { ascending: false });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = (data ?? []).map((a) => ({
      id: a.id,
      name: a.name,
      created_at: a.created_at,
      n_subtypes: a.summary?.n_subtypes,
      n_samples: a.summary?.n_samples,
      survival_pvalue: a.survival_pvalue
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { analyses: rows }
    };
  }
});

// src/lib/mcp/tools/get-analysis-summary.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^3.25.76";
var get_analysis_summary_default = defineTool3({
  name: "get_analysis_summary",
  title: "Get analysis summary",
  description: "Fetch the summary (optimal rank, subtype counts, n_samples) for one saved NMF analysis.",
  inputSchema: { analysisId: z.string().describe("Analysis id from list_analyses.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ analysisId }, ctx) => {
    const err = requireAuth(ctx);
    if (err) return err;
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("analyses").select("id, name, summary, rank_metrics, survival_pvalue, cox_ph_results, created_at").eq("id", analysisId).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Analysis not found" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { analysis: data }
    };
  }
});

// src/lib/mcp/tools/get-marker-genes.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^3.25.76";
var get_marker_genes_default = defineTool4({
  name: "get_marker_genes",
  title: "Get marker genes",
  description: "Return top marker genes per subtype for one saved analysis. topN defaults to 25 per subtype.",
  inputSchema: {
    analysisId: z2.string(),
    topN: z2.number().int().positive().optional().describe("Genes per subtype (default 25)."),
    subtype: z2.string().optional().describe("Filter to a single subtype.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ analysisId, topN, subtype }, ctx) => {
    const err = requireAuth(ctx);
    if (err) return err;
    const sb = supabaseForUser(ctx);
    const limit = topN ?? 25;
    let q = sb.from("analysis_marker_genes").select("gene, subtype, log_fold_change, p_value, rank").eq("analysis_id", analysisId).order("subtype", { ascending: true }).order("rank", { ascending: true });
    if (subtype) q = q.eq("subtype", subtype);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const bySubtype = {};
    for (const row of data ?? []) {
      (bySubtype[row.subtype] ||= []).push(row);
    }
    const trimmed = [];
    for (const s of Object.keys(bySubtype)) trimmed.push(...bySubtype[s].slice(0, limit));
    return {
      content: [{ type: "text", text: JSON.stringify(trimmed, null, 2) }],
      structuredContent: { markerGenes: trimmed }
    };
  }
});

// src/lib/mcp/tools/get-survival-stats.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^3.25.76";
var get_survival_stats_default = defineTool5({
  name: "get_survival_stats",
  title: "Get survival statistics",
  description: "Return log-rank p-value and Cox PH hazard ratios / CIs for one saved analysis.",
  inputSchema: { analysisId: z3.string() },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ analysisId }, ctx) => {
    const err = requireAuth(ctx);
    if (err) return err;
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("analyses").select("survival_pvalue, cox_ph_results").eq("id", analysisId).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Analysis not found" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { survival: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "zvxbojnduszonnmlvojf";
var mcp_default = defineMcp({
  name: "nmf-subtyping-mcp",
  title: "NMF Molecular Subtyping",
  version: "0.1.0",
  instructions: "Access the signed-in user's saved NMF molecular subtyping analyses from the AccelBio dashboard. Start with `list_analyses` to find an analysis id, then call `get_analysis_summary`, `get_marker_genes`, or `get_survival_stats` for details.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [whoami_default, list_analyses_default, get_analysis_summary_default, get_marker_genes_default, get_survival_stats_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
